/**
 * AUTO-GENERATED by scripts/write-build-info.mjs — do not edit by hand.
 * Regenerated on every `npm run build:server` (and `npm run dev`).
 * Tracked in git so a fresh clone typechecks; treat local changes here
 * as build artefacts (commit only when intentional).
 */
export const BUILD_INFO = {
  server_version: "0.1.0",
  build_sha: "b7e9920",
  build_time: "2026-05-08T09:09:44.682Z",
  git_dirty: true,
} as const;
